### ISSUE TITLE
Tall Stack Glitch

### ISSUE THREAD

**Issue by Trashtalk217** [benchislett/projects#1]
When you stack to the top of the screen. As seen here [Here](https://i.imgur.com/J9Uzv5G.png). And you then clear a line. As seen [Here](https://i.imgur.com/uvS91Cm.png). The stack keeps touching the top of the screen as the uppermost line is not being cleared.

**Comment by benchislett** [comment]
Thanks, I'll look into this!

**Comment by benchislett** [comment]
Thanks again for finding this, the bug has been fixed in the [most recent commit](https://github.com/benchislett/projects/commit/dbbaeecaa36286f1eb994577d35f19db4c40783a)
